sudo: false
language: perl
perl:
  - 5.16
  - 5.22

env:
  global:
    - secure: "Yaiv+tTD2FnvN2UwA9yEVIzLQMXR7yhLkuzJ9521MNM354SqKJUFtMLbQfdA7Rld5npylBSl1xfUOwjiraDBvtbjnC6PKpaz2fyR8/ycGptMjbWncxjNiSIxYelmw/JD9qu74Z2yIKzty7O4WqJ1IbP3OrQd/aTYViekibl7hIo="

after_success:
  - ./Build dist
  - export DIST_FILE=$(ls p4-*.tar.gz)
  - export MD5_FILE=$DIST_FILE.md5
  - md5sum $DIST_FILE > $MD5_FILE
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file:
    - $DIST_FILE
    - $MD5_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    perl: 5.16
    tags: true
    all_branches: true
